var h;h||=typeof Module !== 'undefined' ? Module : {};var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="object"==typeof window,fa="function"==typeof importScripts,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,k="",ia,ka,la;
if(ha){var fs=require("fs"),ma=require("path");k=fa?ma.dirname(k)+"/":__dirname+"/";ia=(a,b)=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};la=a=>{a=ia(a,!0);a.buffer||(a=new Uint8Array(a));return a};ka=(a,b,c,d=!0)=>{a=na(a)?new URL(a):ma.normalize(a);fs.readFile(a,d?void 0:"utf8",(e,f)=>{e?c(e):b(d?f.buffer:f)})};!h.thisProgram&&1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));ba=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);
process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof oa||a.context instanceof oa))throw a;});da=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||fa)fa?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?"":k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},fa&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType=
"arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var pa=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var qa;h.wasmBinary&&(qa=h.wasmBinary);
"object"!=typeof WebAssembly&&ra("no native wasm support detected");var sa,n=!1,ta,r,u,ua,va,w,x,y,z;function wa(){var a=sa.buffer;h.HEAP8=r=new Int8Array(a);h.HEAP16=ua=new Int16Array(a);h.HEAPU8=u=new Uint8Array(a);h.HEAPU16=va=new Uint16Array(a);h.HEAP32=w=new Int32Array(a);h.HEAPU32=x=new Uint32Array(a);h.HEAPF32=y=new Float32Array(a);h.HEAPF64=z=new Float64Array(a)}var xa=[],ya=[],za=[],Aa=[];function Ba(){var a=h.preRun.shift();xa.unshift(a)}var Ca=0,Da=null,Ea=null;
function ra(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);n=!0;ta=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Fa=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Ga;Ga="index.wasm";if(!Fa(Ga)){var Ha=Ga;Ga=h.locateFile?h.locateFile(Ha,k):k+Ha}function Ia(a){if(a==Ga&&qa)return new Uint8Array(qa);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}
function Ja(a){if(!qa&&(ea||fa)){if("function"==typeof fetch&&!na(a))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Ia(a));if(ka)return new Promise((b,c)=>{ka(a,d=>b(new Uint8Array(d)),c)})}return Promise.resolve().then(()=>Ia(a))}function Ka(a,b,c){return Ja(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{l(`failed to asynchronously prepare wasm: ${d}`);ra(d)})}
function La(a,b){var c=Ga;qa||"function"!=typeof WebAssembly.instantiateStreaming||Fa(c)||na(c)||ha||"function"!=typeof fetch?Ka(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l(`wasm streaming compile failed: ${e}`);l("falling back to ArrayBuffer instantiation");return Ka(c,a,b)}))}
var Ma,Na,Oa={46280:()=>window.devicePixelRatio,46316:()=>{if(document.pointerLockElement)return 1},46363:()=>{if(document.fullscreenElement)return 1},46409:()=>window.innerWidth,46435:()=>window.innerHeight};function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Pa=a=>{for(;0<a.length;)a.shift()(h)},Qa=h.noExitRuntime||!0,Ra="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,B=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ra)return Ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";
b&&=b.substr(0,b.length-1);return a+b},Va=a=>{if("/"===a)return"/";a=Ta(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Wa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(ha)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}ra("initRandomDevice")},Xa=a=>(Xa=Wa())(a),Ya=(...a)=>{for(var b="",c=!1,d=a.length-
1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Za=[],$a=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=
a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},ab=[];function bb(a,b){ab[a]={input:[],output:[],Xe:b};cb(a,db)}
var db={open(a){var b=ab[a.node.rdev];if(!b)throw new D(43);a.tty=b;a.seekable=!1},close(a){a.tty.Xe.fsync(a.tty)},fsync(a){a.tty.Xe.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Xe.Tf)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Xe.Tf(a.tty)}catch(m){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Xe.Hf)throw new D(60);try{for(var e=0;e<d;e++)a.tty.Xe.Hf(a.tty,b[c+
e])}catch(f){throw new D(29);}d&&(a.node.timestamp=Date.now());return e}},eb={Tf(){a:{if(!Za.length){var a=null;if(ha){var b=Buffer.alloc(256);a=0;var c=process.stdin.fd;try{a=fs.readSync(c,b)}catch(d){if(d.toString().includes("EOF"))a=0;else throw d;}a=0<a?b.slice(0,a).toString("utf-8"):null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){b=null;break a}b=Array($a(a)+
1);a=C(a,b,0,b.length);b.length=a;Za=b}b=Za.shift()}return b},Hf(a,b){null===b||10===b?(pa(B(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(B(a.output,0)),a.output=[])},kg(){return{Ag:25856,Cg:5,zg:191,Bg:35387,yg:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},lg(){return 0},mg(){return[24,80]}},fb={Hf(a,b){null===b||10===b?(l(B(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(l(B(a.output,
0)),a.output=[])}};function gb(a,b){var c=a.Pe?a.Pe.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Pe,a.Pe=new Uint8Array(b),0<a.Qe&&a.Pe.set(c.subarray(0,a.Qe),0))}
var E={Te:null,We(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);E.Te||(E.Te={dir:{node:{$e:E.Oe.$e,Ue:E.Oe.Ue,lookup:E.Oe.lookup,pf:E.Oe.pf,rename:E.Oe.rename,unlink:E.Oe.unlink,rmdir:E.Oe.rmdir,readdir:E.Oe.readdir,symlink:E.Oe.symlink},stream:{bf:E.xe.bf}},file:{node:{$e:E.Oe.$e,Ue:E.Oe.Ue},stream:{bf:E.xe.bf,read:E.xe.read,write:E.xe.write,Nf:E.xe.Nf,Vf:E.xe.Vf,sf:E.xe.sf}},link:{node:{$e:E.Oe.$e,Ue:E.Oe.Ue,readlink:E.Oe.readlink},
stream:{}},Of:{node:{$e:E.Oe.$e,Ue:E.Oe.Ue},stream:hb}});c=ib(a,b,c,d);16384===(c.mode&61440)?(c.Oe=E.Te.dir.node,c.xe=E.Te.dir.stream,c.Pe={}):32768===(c.mode&61440)?(c.Oe=E.Te.file.node,c.xe=E.Te.file.stream,c.Qe=0,c.Pe=null):40960===(c.mode&61440)?(c.Oe=E.Te.link.node,c.xe=E.Te.link.stream):8192===(c.mode&61440)&&(c.Oe=E.Te.Of.node,c.xe=E.Te.Of.stream);c.timestamp=Date.now();a&&(a.Pe[b]=c,a.timestamp=c.timestamp);return c},Hg(a){return a.Pe?a.Pe.subarray?a.Pe.subarray(0,a.Qe):new Uint8Array(a.Pe):
new Uint8Array(0)},Oe:{$e(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.Qe:40960===(a.mode&61440)?a.link.length:0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.eg=4096;b.blocks=Math.ceil(b.size/b.eg);return b},Ue(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,
a.Qe!=b))if(0==b)a.Pe=null,a.Qe=0;else{var c=a.Pe;a.Pe=new Uint8Array(b);c&&a.Pe.set(c.subarray(0,Math.min(b,a.Qe)));a.Qe=b}},lookup(){throw jb[44];},pf(a,b,c,d){return E.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=kb(b,c)}catch(f){}if(d)for(var e in d.Pe)throw new D(55);}delete a.parent.Pe[a.name];a.parent.timestamp=Date.now();a.name=c;b.Pe[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink(a,b){delete a.Pe[b];a.timestamp=Date.now()},rmdir(a,b){var c=kb(a,b),d;for(d in c.Pe)throw new D(55);
delete a.Pe[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.Pe))b.push(c);return b},symlink(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new D(28);return a.link}},xe:{read(a,b,c,d,e){var f=a.node.Pe;if(e>=a.node.Qe)return 0;a=Math.min(a.node.Qe-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===r.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=
Date.now();if(b.subarray&&(!a.Pe||a.Pe.subarray)){if(f)return a.Pe=b.subarray(c,c+d),a.Qe=d;if(0===a.Qe&&0===e)return a.Pe=b.slice(c,c+d),a.Qe=d;if(e+d<=a.Qe)return a.Pe.set(b.subarray(c,c+d),e),d}gb(a,e+d);if(a.Pe.subarray&&b.subarray)a.Pe.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Pe[e+f]=b[c+f];a.Qe=Math.max(a.Qe,e+d);return d},bf(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Qe);if(0>b)throw new D(28);return b},Nf(a,b,c){gb(a.node,b+c);a.node.Qe=Math.max(a.node.Qe,
b+c)},Vf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.Pe;if(e&2||a.buffer!==r.buffer){if(0<c||c+b<a.length)a=a.subarray?a.subarray(c,c+b):Array.prototype.slice.call(a,c,c+b);c=!0;b=65536*Math.ceil(b/65536);(e=lb(65536,b))?(u.fill(0,e,e+b),b=e):b=0;if(!b)throw new D(48);r.set(a,b)}else c=!1,b=a.byteOffset;return{Sg:b,tg:c}},sf(a,b,c,d){E.xe.write(a,b,0,d,c,!1);return 0}}},mb=h.preloadPlugins||[],nb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ob=null,pb={},qb=[],rb=1,sb=
null,tb=!0,D=class{constructor(a){this.name="ErrnoError";this.Se=a}},jb={},ub=class{constructor(){this.vf={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.vf.flags}set flags(a){this.vf.flags=a}get position(){return this.vf.position}set position(a){this.vf.position=a}},vb=class{constructor(a,b,c,d){a||=this;this.parent=a;this.We=a.We;this.qf=null;this.id=rb++;this.name=b;this.mode=c;this.Oe={};this.xe={};this.rdev=d;this.tf=365;this.yf=146}get read(){return(this.mode&
this.tf)===this.tf}set read(a){a?this.mode|=this.tf:this.mode&=~this.tf}get write(){return(this.mode&this.yf)===this.yf}set write(a){a?this.mode|=this.yf:this.mode&=~this.yf}};
function wb(a,b={}){a=Ya(a);if(!a)return{path:"",node:null};b=Object.assign({Qf:!0,If:0},b);if(8<b.If)throw new D(32);a=a.split("/").filter(g=>!!g);for(var c=ob,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=kb(c,a[e]);d=Ta(d+"/"+a[e]);c.qf&&(!f||f&&b.Qf)&&(c=c.qf.root);if(!f||b.Cf)for(f=0;40960===(c.mode&61440);)if(c=xb(d),d=Ya(Ua(d),c),c=wb(d,{If:b.If+1}).node,40<f++)throw new D(32);}return{path:d,node:c}}
function yb(a){for(var b;;){if(a===a.parent)return a=a.We.Wf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%sb.length}function kb(a,b){var c=16384===(a.mode&61440)?(c=Ab(a,"x"))?c:a.Oe.lookup?0:2:54;if(c)throw new D(c);for(c=sb[zb(a.id,b)];c;c=c.pg){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Oe.lookup(a,b)}
function ib(a,b,c,d){a=new vb(a,b,c,d);b=zb(a.parent.id,a.name);a.pg=sb[b];return sb[b]=a}function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ab(a,b){if(tb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Cb(a,b){try{return kb(a,b),20}catch(c){}return Ab(a,"wx")}function F(a){a=qb[a];if(!a)throw new D(8);return a}
function Db(a,b=-1){a=Object.assign(new ub,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!qb[b])break a;throw new D(33);}a.fd=b;return qb[b]=a}function Eb(a,b=-1){a=Db(a,b);a.xe?.Eg?.(a);return a}var hb={open(a){a.xe=pb[a.node.rdev].xe;a.xe.open?.(a)},bf(){throw new D(70);}};function cb(a,b){pb[a]={xe:b}}
function Fb(a,b){var c="/"===b;if(c&&ob)throw new D(10);if(!c&&b){var d=wb(b,{Qf:!1});b=d.path;d=d.node;if(d.qf)throw new D(10);if(16384!==(d.mode&61440))throw new D(54);}b={type:a,Rg:{},Wf:b,og:[]};a=a.We(b);a.We=b;b.root=a;c?ob=a:d&&(d.qf=b,d.We&&d.We.og.push(b))}function Gb(a,b,c){var d=wb(a,{parent:!0}).node;a=Va(a);if(!a||"."===a||".."===a)throw new D(28);var e=Cb(d,a);if(e)throw new D(e);if(!d.Oe.pf)throw new D(63);return d.Oe.pf(d,a,b,c)}function G(a){return Gb(a,16895,0)}
function Hb(a,b,c){"undefined"==typeof c&&(c=b,b=438);Gb(a,b|8192,c)}function Ib(a,b){if(!Ya(a))throw new D(44);var c=wb(b,{parent:!0}).node;if(!c)throw new D(44);b=Va(b);var d=Cb(c,b);if(d)throw new D(d);if(!c.Oe.symlink)throw new D(63);c.Oe.symlink(c,b,a)}function xb(a){a=wb(a).node;if(!a)throw new D(44);if(!a.Oe.readlink)throw new D(28);return Ya(yb(a.parent),a.Oe.readlink(a))}
function Jb(a,b,c){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ta(a);try{e=wb(a,{Cf:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new D(20);}else e=Gb(a,c,0),d=!0;if(!e)throw new D(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new D(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Bb(b)||b&512)?31:Ab(e,Bb(b)):44))throw new D(c);if(b&512&&!d){c=e;c="string"==typeof c?wb(c,{Cf:!0}).node:c;if(!c.Oe.Ue)throw new D(63);if(16384===(c.mode&61440))throw new D(31);if(32768!==(c.mode&61440))throw new D(28);if(d=Ab(c,"w"))throw new D(d);c.Oe.Ue(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Db({node:e,path:yb(e),flags:b,seekable:!0,position:0,xe:e.xe,rg:[],error:!1});e.xe.open&&e.xe.open(e);!h.logReadFiles||b&1||(Kb||=
{},a in Kb||(Kb[a]=1));return e}function Lb(a){if(null===a.fd)throw new D(8);a.Ff&&(a.Ff=null);try{a.xe.close&&a.xe.close(a)}catch(b){throw b;}finally{qb[a.fd]=null}a.fd=null}function Mb(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.xe.bf)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.xe.bf(a,b,c);a.rg=[]}
function Nb(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(16384===(a.node.mode&61440))throw new D(31);if(!a.xe.write)throw new D(28);a.seekable&&a.flags&1024&&Mb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.xe.write(a,b,c,d,e,f);g||(a.position+=b);return b}var Ob;
function Pb(){var a="/";a="string"==typeof a?a:yb(a);for(var b=[".glfw_dropped_files"].reverse();b.length;){var c=b.pop();if(c){a=Ta(a+"/"+c);try{G(a)}catch(d){}}}}
function Qb(a,b,c){a=Ta("/dev/"+a);var d=nb(!!b,!!c);Rb||=64;var e=Rb++<<8|0;cb(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,m,p){for(var q=0,v=0;v<p;v++){try{var t=b()}catch(A){throw new D(29);}if(void 0===t&&0===q)throw new D(6);if(null===t||void 0===t)break;q++;g[m+v]=t}q&&(f.node.timestamp=Date.now());return q},write(f,g,m,p){for(var q=0;q<p;q++)try{c(g[m+q])}catch(v){throw new D(29);}p&&(f.node.timestamp=Date.now());return q}});Hb(a,d,e)}var Rb,H={},Kb;
function Sb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":F(a).path;if(0==b.length)throw new D(44);return Ta(a+"/"+b)}var Tb=void 0;function I(){var a=w[+Tb>>2];Tb+=4;return a}var Ub=[],Vb=(a,b)=>{Ub.length=0;for(var c;c=u[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Ub.push(112==c?x[b>>2]:105==c?w[b>>2]:z[b>>3]);b+=d?8:4}return Ub},Wb=0,Xb=[];
function Yb(){if(navigator.userActivation?navigator.userActivation.isActive:Wb&&Zb.Af)for(var a=0;a<Xb.length;++a){var b=Xb[a];Xb.splice(a,1);--a;b.Ug(...b.vg)}}var $b=[];function ac(a){var b=$b[a];b.target.removeEventListener(b.Re,b.Pf,b.Ye);$b.splice(a,1)}function bc(a){if(!a.target)return-4;if(a.Ze)a.Pf=function(c){++Wb;Zb=a;Yb();a.af(c);Yb();--Wb},a.target.addEventListener(a.Re,a.Pf,a.Ye),$b.push(a);else for(var b=0;b<$b.length;++b)$b[b].target==a.target&&$b[b].Re==a.Re&&ac(b--);return 0}
function cc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Zb,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],J=a=>{a=2<a?a?B(u,a):"":a;return nc[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},oc=a=>0>nc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},pc=(a,b)=>{z[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)z[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)z[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+
4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;C(b.id,u,a+1304,64);C(b.mapping,u,a+1368,64)},qc;qc=()=>performance.now();
var rc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},sc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
tc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wc=1,xc=[],K=[],yc=[],zc=[],Ac=[],L=[],Bc=[],Cc=[],M=[],Dc={},Ec=4,Fc=a=>{for(var b=wc++,c=a.length;c<b;c++)a[c]=null;return b},Gc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=N[c](),g=f&&Fc(d);f?(f.name=g,d[g]=f):P||=1282;w[b+4*e>>2]=g}},Ic=(a,b)=>{a.Sf||(a.Sf=a.getContext,a.getContext=function(d,e){e=a.Sf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Hc(c,b):0},Hc=(a,b)=>{var c=
Fc(Cc),d={handle:c,attributes:b,version:b.ng,zf:a};a.canvas&&(a.canvas.sg=d);Cc[c]=d;("undefined"==typeof b.hg||b.hg)&&Jc(d);return c},Jc=a=>{a||=Kc;if(!a.ig){a.ig=!0;var b=a.zf;rc(b);sc(b);tc(b);b.Ve=b.getExtension("EXT_disjoint_timer_query");b.Og=b.getExtension("WEBGL_multi_draw");vc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},Lc={},P,Kc,Mc=a=>N.activeTexture(a),Nc=(a,b)=>{N.attachShader(K[a],L[b])},Oc=(a,b,c)=>{N.bindAttribLocation(K[a],b,c?B(u,c):"")},
Pc=(a,b)=>{N.bindBuffer(a,xc[b])},Qc=(a,b)=>{N.bindTexture(a,Ac[b])},Rc=(a,b)=>N.blendFunc(a,b),Sc=(a,b,c,d)=>{N.bufferData(a,c?u.subarray(c,c+b):b,d)},Tc=(a,b,c,d)=>{N.bufferSubData(a,b,u.subarray(d,d+c))},Uc=a=>N.clear(a),Vc=(a,b,c,d)=>N.clearColor(a,b,c,d),Wc=a=>N.clearDepth(a),Xc=a=>{N.compileShader(L[a])},Yc=(a,b,c,d,e,f,g,m)=>{N.compressedTexImage2D(a,b,c,d,e,f,m?u.subarray(m,m+g):null)},Zc=()=>{var a=Fc(K),b=N.createProgram();b.name=a;b.nf=b.lf=b.mf=0;b.Lf=1;K[a]=b;return a},$c=a=>{var b=Fc(L);
L[b]=N.createShader(a);return b},ad=a=>N.cullFace(a),bd=(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=xc[d];e&&(N.deleteBuffer(e),e.name=0,xc[d]=null)}},cd=a=>{if(a){var b=K[a];b?(N.deleteProgram(b),b.name=0,K[a]=null):P||=1281}},dd=a=>{if(a){var b=L[a];b?(N.deleteShader(b),L[a]=null):P||=1281}},ed=(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Ac[d];e&&(N.deleteTexture(e),e.name=0,Ac[d]=null)}},fd=a=>N.depthFunc(a),gd=(a,b)=>{N.detachShader(K[a],L[b])},hd=a=>N.disable(a),jd=a=>{N.disableVertexAttribArray(a)},
kd=(a,b,c)=>{N.drawArrays(a,b,c)},ld=[],md=(a,b,c,d)=>{N.drawElements(a,b,c,d)},nd=a=>N.enable(a),od=a=>{N.enableVertexAttribArray(a)},pd=a=>N.frontFace(a),qd=(a,b)=>{Gc(a,b,"createBuffer",xc)},rd=(a,b)=>{Gc(a,b,"createTexture",Ac)},sd=(a,b,c,d,e,f,g,m)=>{b=K[b];if(a=N[a](b,c))d=m&&C(a.name,u,m,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)},td=(a,b)=>N.getAttribLocation(K[a],b?B(u,b):""),ud=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(P||=1280);return;
case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":P||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:P||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+
4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:r[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;x[b>>2]=c;x[b+4>>2]=(c-x[b>>2])/4294967296;break;case 0:w[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:r[b]=d?1:
0}}else P||=1281},vd=(a,b)=>ud(a,b,2),wd=(a,b,c,d)=>{a=N.getProgramInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,u,d,b):0;c&&(w[c>>2]=b)},xd=(a,b,c)=>{if(c)if(a>=wc)P||=1281;else if(a=K[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==b){if(!a.nf)for(b=0;b<N.getProgramParameter(a,35718);++b)a.nf=Math.max(a.nf,N.getActiveUniform(a,b).name.length+1);w[c>>2]=a.nf}else if(35722==b){if(!a.lf)for(b=0;b<N.getProgramParameter(a,35721);++b)a.lf=
Math.max(a.lf,N.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.lf}else if(35381==b){if(!a.mf)for(b=0;b<N.getProgramParameter(a,35382);++b)a.mf=Math.max(a.mf,N.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.mf}else w[c>>2]=N.getProgramParameter(a,b);else P||=1281},yd=(a,b,c)=>{c?(a=N.Ve.getQueryObjectEXT(M[a],b),a="boolean"==typeof a?a?1:0:a,x[c>>2]=a,x[c+4>>2]=(a-x[c>>2])/4294967296):P||=1281},zd=(a,b,c)=>{c?(a=N.Ve.getQueryObjectEXT(M[a],b),w[c>>2]="boolean"==typeof a?a?1:0:a):P||=1281},Ad=(a,
b,c,d)=>{a=N.getShaderInfoLog(L[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,u,d,b):0;c&&(w[c>>2]=b)},Bd=(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(L[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(L[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=N.getShaderParameter(L[a],b):P||=1281},Cd=a=>{var b=$a(a)+1,c=Q(b);c&&C(a,u,c,b);return c};function Dd(){var a=vc(N);return a=a.concat(a.map(b=>"GL_"+b))}
var Ed=a=>{var b=Dc[a];if(!b){switch(a){case 7939:b=Cd(Dd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||(P||=1280);b=b?Cd(b):0;break;case 7938:b=Cd(`OpenGL ES 2.0 (${N.getParameter(7938)})`);break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Cd(b);break;default:P||=1280}Dc[a]=b}return b},Fd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),
Gd=a=>{var b=a.gf,c=a.ag,d;if(!b)for(a.gf=b={},a.$f={},d=0;d<N.getProgramParameter(a,35718);++d){var e=N.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Fd(f);g=0<g?f.slice(0,g):f;var m=a.Lf;a.Lf+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.$f[m++]=g}},Hd=(a,b)=>{b=b?B(u,b):"";if(a=K[a]){Gd(a);var c=a.gf,d=0,e=b,f=Fd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ag[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else P||=1281;return-1},R=a=>{var b=N.gg;if(b){var c=
b.gf[a];"number"==typeof c&&(b.gf[a]=c=N.getUniformLocation(b,b.$f[a]+(0<c?`[${c}]`:"")));return c}P||=1282},Id=(a,b,c,d)=>{if(c)if(a=K[a],Gd(a),a=N.getUniform(a,R(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else P||=1281},Jd=(a,b,c,d)=>{if(c)if(a=N.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>
2]=a;break;case 2:y[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else P||=1281},Kd=a=>{a=K[a];N.linkProgram(a);a.gf=0;a.ag={}},Ld=(a,b)=>{3317==a&&(Ec=b);N.pixelStorei(a,b)},Md=(a,b,c,d,e)=>{a-=5120;a=1==a?u:4==a?w:6==a?y:5==a||28922==a?x:va;var f=Ec;b=d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+f-1&-f);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),
e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},Nd=(a,b,c,d,e,f,g)=>{(g=Md(f,e,c,d,g))?N.readPixels(a,b,c,d,e,f,g):P||=1280},Od=(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=x[c+4*f>>2])?B(u,g,d?x[d+4*f>>2]:void 0):"";e+=g}N.shaderSource(L[a],e)},Pd=(a,b,c,d,e,f,g,m,p)=>{N.texImage2D(a,b,c,d,e,f,g,m,p?Md(m,g,d,e,p):null)},Qd=(a,b,c)=>N.texParameteri(a,b,c),Rd=[],Sd=(a,b)=>{N.uniform1i(R(a),b)},Td=[],Ud=(a,b,c,d,e)=>{N.uniform4f(R(a),b,c,d,e)},Vd=(a,b,c,d)=>{if(18>=b){var e=Rd[16*b-1],f=y;d>>=2;for(var g=
0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=y.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(R(a),!!c,e)},Wd=a=>{a=K[a];N.useProgram(a);N.gg=a},Xd=(a,b,c,d,e,f)=>{N.vertexAttribPointer(a,b,c,!!d,e,f)},Yd=(a,b,c,d)=>N.viewport(a,b,c,d),Zd=()=>{try{if(navigator.getGamepads)return(dc=
navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},$d=(a,b,c,d,e,f)=>{ec||=Q(256);a={target:J(a),Re:f,Ze:d,af:(g=event)=>{var m=g.target.id?g.target.id:"",p=ec;C(cc(g.target),u,p+0,128);C(m,u,p+128,128);S(d,e,p,b)&&g.preventDefault()},Ye:c};return bc(a)},ae=(a,b,c,d,e,f)=>{fc||=Q(72);a=J(a);return bc({target:a,Af:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Re:f,Ze:d,af:(g=event)=>{var m=a,p=fc;z[p>>3]=g.timeStamp;p>>=2;w[p+2]=g.screenX;w[p+3]=g.screenY;w[p+4]=g.clientX;
w[p+5]=g.clientY;w[p+6]=g.ctrlKey;w[p+7]=g.shiftKey;w[p+8]=g.altKey;w[p+9]=g.metaKey;ua[2*p+20]=g.button;ua[2*p+21]=g.buttons;w[p+11]=g.movementX;w[p+12]=g.movementY;m=oc(m);w[p+13]=g.clientX-(m.left|0);w[p+14]=g.clientY-(m.top|0);S(d,e,fc,b)&&g.preventDefault()},Ye:c})},be=(a,b,c,d,e)=>{hc||=Q(280);return bc({target:a,Re:e,Ze:d,af:(f=event)=>{var g=hc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!m;w[g>>2]=p;w[g+4>>
2]=document.fullscreenEnabled||document.webkitFullscreenEnabled;var q=p?m:gc,v=q?.id||"";C(cc(q),u,g+8,128);C(v,u,g+136,128);w[g+264>>2]=q?q.clientWidth:0;w[g+268>>2]=q?q.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;p&&(gc=m);S(d,19,g,b)&&f.preventDefault()},Ye:c})},ce=(a,b,c,d,e)=>{ic||=Q(1432);b={target:J(2),Af:!0,Re:e,Ze:c,af:(f=event)=>{var g=ic;pc(g,f.gamepad);S(c,d,g,a)&&f.preventDefault()},Ye:b};return bc(b)},de=(a,b,c,d,e)=>{jc||=Q(260);return bc({target:a,Re:e,Ze:d,af:(f=
event)=>{var g=jc,m=document.pointerLockElement||document.Kg||document.Yg||document.Mg;w[g>>2]=!!m;var p=m?.id||"";C(cc(m),u,g+4,128);C(p,u,g+132,128);S(d,20,g,b)&&f.preventDefault()},Ye:c})},ee=(a,b,c,d)=>{kc||=Q(36);a=J(a);return bc({target:a,Re:"resize",Ze:d,af:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=kc;w[g>>2]=0;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset|0;
w[g+32>>2]=pageYOffset|0;S(d,10,g,b)&&e.preventDefault()}}},Ye:c})},fe=(a,b,c,d,e,f)=>{lc||=Q(1696);a=J(a);return bc({target:a,Af:"touchstart"==f||"touchend"==f,Re:f,Ze:d,af:g=>{for(var m,p={},q=g.touches,v=0;v<q.length;++v)m=q[v],m.Uf=m.Xf=0,p[m.identifier]=m;for(v=0;v<g.changedTouches.length;++v)m=g.changedTouches[v],m.Uf=1,p[m.identifier]=m;for(v=0;v<g.targetTouches.length;++v)p[g.targetTouches[v].identifier].Xf=1;q=lc;z[q>>3]=g.timeStamp;var t=q>>2;w[t+3]=g.ctrlKey;w[t+4]=g.shiftKey;w[t+5]=g.altKey;
w[t+6]=g.metaKey;t+=7;var A=oc(a),O=0;for(v in p)if(m=p[v],w[t+0]=m.identifier,w[t+1]=m.screenX,w[t+2]=m.screenY,w[t+3]=m.clientX,w[t+4]=m.clientY,w[t+5]=m.pageX,w[t+6]=m.pageY,w[t+7]=m.Uf,w[t+8]=m.Xf,w[t+9]=m.clientX-(A.left|0),w[t+10]=m.clientY-(A.top|0),t+=13,31<++O)break;w[q+8>>2]=O;S(d,e,q,b)&&g.preventDefault()},Ye:c})},ge=(a,b,c)=>{var d=nc[1];mc||=Q(8);return bc({target:d,Re:"visibilitychange",Ze:c,af:(e=event)=>{var f=mc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);
w[f>>2]=document.hidden;w[f+4>>2]=g;S(c,21,f,a)&&e.preventDefault()},Ye:b})},qe=(a,b)=>{he=a;ie=b;if(je)if(ke||=!0,0==a)le=function(){var d=Math.max(0,me+b-qc())|0;setTimeout(ne,d)};else if(1==a)le=function(){oe(ne)};else if(2==a){if("undefined"==typeof pe)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);pe=function(d){c.push(d);fa?(void 0===h.setImmediates&&(h.setImmediates=
[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate","*")}}else pe=setImmediate;le=function(){pe(ne)}}},xe=a=>{je=a;var b=re;ke=!1;ne=function(){if(!n)if(0<se.length){var c=se.shift();c.Gg(c.ug);if(te){var d=te,e=0==d%1?d-1:Math.floor(d);te=c.Dg?e:(8*d+(e+.5))/9}h.setStatus&&(c=h.statusMessage||"Please wait...",d=te,e=ue.Fg,d?d<e?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(c):h.setStatus(""));b<re||setTimeout(ne,0)}else b<re||(ve=
ve+1|0,1==he&&1<ie&&0!=ve%ie?le():(0==he&&(me=qc()),n||h.preMainLoop&&!1===h.preMainLoop()||(we(a),h.postMainLoop?.()),b<re||("object"==typeof SDL&&SDL.audio?.Tg?.(),le())))}},ye=a=>{a instanceof oa||"unwind"==a||da(1,a)},ze=0,Ae=a=>{ta=a;Qa||0<ze||(h.onExit?.(a),n=!0);da(a,new oa(a))},Be=a=>{ta=a;Ae(a)},we=a=>{if(!n)try{if(a(),!(Qa||0<ze))try{ta=a=ta,Ae(a)}catch(b){ye(b)}}catch(b){ye(b)}},Ce=(a,b)=>setTimeout(()=>{we(a)},b),ke=!1,le=null,re=0,je=null,he=0,ie=0,ve=0,se=[];
function De(){le=null;re++}function Ee(){re++;var a=he,b=ie,c=je;je=null;xe(c);qe(a,b);le()}var ue={},me,ne,te,Fe=!1,Ge=!1,He=[];
function Ie(){function a(){Ge=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Je){Je=!0;mb.push({canHandle:function(c){return!h.Qg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Ke(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Ke(d)}));var m=URL.createObjectURL(g),p=new Image;p.onload=()=>{var q=document.createElement("canvas");
q.width=p.width;q.height=p.height;q.getContext("2d").drawImage(p,0,0);URL.revokeObjectURL(m);e?.(c)};p.onerror=()=>{l(`Image ${m} could not be decoded`);f?.()};p.src=m}});mb.push({canHandle:function(c){return!h.Pg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Ke(d)})),p=new Audio;p.addEventListener("canplaythrough",()=>f(p),!1);p.onerror=function(){if(!g){l(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var q="",v=0,t=0,A=0;A<c.length;A++)for(v=v<<8|c[A],t+=8;6<=t;){var O=v>>t-6&63;t-=6;q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[O]}2==t?(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&3)<<4],q+="=="):4==t&&(q+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(v&15)<<2],q+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+q;f(p)}};p.src=m;Ce(()=>{f(p)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Ge&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function Le(a,b,c,d){if(b&&h.cf&&a==h.canvas)return h.cf;var e;if(b){var f={antialias:!1,alpha:!1,ng:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Lc&&(e=Ic(a,f)))var m=Cc[e].zf}else m=a.getContext("2d");if(!m)return null;c&&(h.cf=m,b&&(Kc=Cc[e],h.cf=N=Kc?.zf),h.Xg=b,He.forEach(p=>p()),Ie());return m}var Me=!1,Ne=void 0,T=void 0;
function Oe(a,b){function c(){Fe=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Pe,Ne&&d.requestPointerLock(),Fe=!0,T?Qe():Re(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),T?Se():Re(d));h.onFullScreen?.(Fe);h.onFullscreen?.(Fe)}Ne=a;T=b;"undefined"==typeof Ne&&(Ne=!0);"undefined"==typeof T&&(T=!1);var d=h.canvas;Me||(Me=
!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?
()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}function Pe(){if(!Fe)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Te=0;function oe(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Te)Te=b+1E3/60;else for(;b+2>=Te;)Te+=1E3/60;setTimeout(a,Math.max(Te-b,0))}}
function Ke(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Ue=0,Ve=0,We=0,Xe=0;function Ye(a,b){var c=h.canvas.getBoundingClientRect(),d=h.canvas.height;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=h.canvas.width/c.width;b*=d/c.height;return{x:a,y:b}}
function Ze(a,b){const {x:c,y:d}=Ye(a,b);We=c-Ue;Xe=d-Ve;Ue=c;Ve=d}function $e(a){Ge?("mousemove"!=a.type&&"mozMovementX"in a?We=Xe=0:(We=a.movementX||a.mozMovementX||a.webkitMovementX||0,Xe=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Ue=SDL.Ig+We,Ve=SDL.Jg+Xe):(Ue+=We,Ve+=Xe)):"touchstart"===a.type||"touchend"===a.type||"touchmove"===a.type?(a=a.Vg,void 0!==a&&Ye(a.pageX,a.pageY)):Ze(a.pageX,a.pageY)}var af=[];
function bf(){var a=h.canvas;af.forEach(b=>b(a.width,a.height))}function cf(a,b,c){Re(h.canvas,a,b);c||bf()}function Qe(){"undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608);Re(h.canvas);bf()}function Se(){"undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]&-8388609);Re(h.canvas);bf()}
function Re(a,b,c){b&&c?(a.Mf=b,a.Gf=c):(b=a.Mf,c=a.Gf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}T?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var df={},pe,Je;
function ef(a,b,c,d,e,f,g){this.id=a;this.y=this.x=0;this.jf=!1;this.Zf=this.Yf=0;this.width=b;this.height=c;this.Ef=d;this.Df=e;this.Kf=b;this.Jf=c;this.title=f;this.share=g;this.attributes=Object.assign({},ff);this.buttons=0;this.keys=[];this.Bf=[];this.qg=0;this.title=null;this.hf=this.kf=this.ff=this.uf=this.df=this.ef=this.rf=this.wf=this.Rf=this.dg=this.cg=this.bg=this.xf=0}
var V=a=>0>=a||!U?null:U[a-1],gf=0,W=null,hf=null,U=null,jf=null,kf=null,ff=null,lf=null,mf={131073:0,131074:0,131075:1,131076:1,131077:1,131082:0,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0,139276:0},nf=a=>{switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;
case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;
case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 96;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;
case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;
case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 224:return 343;case 93:return 348;
default:return-1}},of=()=>{var a=W,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);if(a.keys[343]||a.keys[348])b|=8;return b},pf=a=>{W&&W.hf&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||dynCall_vii(W.hf,W.id,a))},rf=(a,b)=>{if(W){var c=nf(a);if(-1!=c){var d=b&&W.keys[c];W.keys[c]=b;W.Bf[a]=b;W.kf&&(d&&(b=2),qf(W.kf,W.id,c,a,b,of()))}}},tf=()=>{sf()},uf=()=>{sf()},vf=a=>{rf(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()},wf=a=>{rf(a.keyCode,0)},xf=()=>{if(W)for(var a=
0;a<W.Bf.length;++a)W.Bf[a]&&rf(a,0)},zf=a=>{if(W){if("touchmove"===a.type){a.preventDefault();let b=!1;for(let c of a.changedTouches)if(lf===c.identifier){Ze(c.pageX,c.pageY);b=!0;break}if(!b)return}else $e(a);a.target==h.canvas&&W.ef&&W.ef&&yf(W.ef,W.id,Ue,Ve)}},Af=a=>{W&&a.target==h.canvas&&W.df&&dynCall_vii(W.df,W.id,1)},Bf=a=>{W&&a.target==h.canvas&&W.df&&dynCall_vii(W.df,W.id,0)},Ef=(a,b)=>{if(W&&a.target==h.canvas){var c=0;if("touchstart"===a.type||"touchend"===a.type||"touchcancel"===a.type){a.preventDefault();
var d=!1;if(null===lf&&"touchstart"===a.type&&0<a.targetTouches.length)d=a.targetTouches[0],lf=d.identifier,Ze(d.pageX,d.pageY),d=!0;else if("touchend"===a.type||"touchcancel"===a.type)for(let e of a.changedTouches)if(lf===e.identifier){lf=null;d=!0;break}if(!d)return}else $e(a),c=a.button,0<c&&(c=1==c?2:1);if(1==b){W.buttons|=1<<c;try{a.target.setCapture()}catch(e){}}else W.buttons&=~(1<<c);W.rf&&Df(W.rf,W.id,c,b,of())}},Ff=a=>{W&&Ef(a,1)},Gf=a=>{W&&Ef(a,0)},Hf=a=>{switch(a.type){case "DOMMouseScroll":var b=
a.detail/3;break;case "mousewheel":b=a.wheelDelta/120;break;case "wheel":b=a.deltaY;switch(a.deltaMode){case 0:b/=100;break;case 1:b/=3;break;case 2:b*=80;break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}b=-b;b=0==b?0:0<b?Math.max(b,1):Math.min(b,-1);W&&W.uf&&a.target==h.canvas&&(yf(W.uf,W.id,"mousewheel"==a.type?a.wheelDeltaX:a.deltaX,b),a.preventDefault())},Jf=(a,b,c,d)=>{if(W){var e=!1;document.fullscreen||document.fullScreen||
document.mozFullScreen||document.webkitIsFullScreen?W.jf||(e=a!=screen.width||b!=screen.height,W.Yf=W.x,W.Zf=W.y,W.Kf=W.width,W.Jf=W.height,W.x=W.y=0,W.width=screen.width,W.height=screen.height,W.jf=!0):1==W.jf&&(e=a!=W.Kf||b!=W.Jf,W.x=W.Yf,W.y=W.Zf,W.width=W.Kf,W.height=W.Jf,W.jf=!1);if(e)cf(W.width,W.height);else if(W.width!=a||W.height!=b||W.Ef!=c||W.Df!=d)W.width=a,W.height=b,W.Ef=c,W.Df=d,W&&W.xf&&If(W.xf,W.id,W.width,W.height),W&&W.Rf&&If(W.Rf,W.id,W.Ef,W.Df)}},Kf={},Lf=[],Mf=null,sf=()=>{if(ve!==
Mf||!ve){Lf=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads||[];Mf=ve;for(var a=0;a<Lf.length;++a){var b=Lf[a];if(b){Kf[a]||(pa("glfw joystick connected:",a),Kf[a]={id:Cd(b.id),xg:b.buttons.length,wg:b.axes.length,buttons:Q(b.buttons.length),axes:Q(4*b.axes.length)});for(var c=Kf[a],d=0;d<b.buttons.length;++d)r[c.buttons+d]=b.buttons[d].pressed;for(d=0;d<b.axes.length;++d)y[c.axes+4*d>>2]=b.axes[d]}else Kf[a]&&(pa("glfw joystick disconnected",a),Nf(Kf[a].id),Nf(Kf[a].buttons),
Nf(Kf[a].axes),delete Kf[a])}}},Of=a=>{function b(m){var p="/.glfw_dropped_files/"+m.name.replace(/\//g,"_"),q=new FileReader;q.onloadend=t=>{if(2!=q.readyState)++f,pa("failed to read dropped file: "+m.name+": "+q.error);else{var A=new Uint8Array(t.target.result);t={};t.flags=t.flags||577;var O=Jb(p,t.flags,t.mode);if("string"==typeof A){var ja=new Uint8Array($a(A)+1);A=C(A,ja,0,ja.length);Nb(O,ja,0,A,void 0,t.fg)}else if(ArrayBuffer.isView(A))Nb(O,A,0,A.byteLength,void 0,t.fg);else throw Error("Unsupported data type");
Lb(O);if(++f===e){If(W.ff,W.id,e,c);for(t=0;t<d.length;++t)Nf(d[t]);Nf(c)}}};q.readAsArrayBuffer(m);var v=Cd(p);d.push(v);x[c+4*g>>2]=v}if(W&&W.ff&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Q(4*a.dataTransfer.files.length),d=[],e=a.dataTransfer.files.length,f=0;Pb();for(var g=0;g<e;++g)b(a.dataTransfer.files[g]);return!1}},Pf=a=>{if(W&&W.ff)return a.preventDefault(),!1};
function Qf(a,b){function c(){Fe=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Pe,Ne&&d.requestPointerLock(),Fe=!0,T?Qe():(Re(d),bf())):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),T?Se():(Re(d),bf()));if(h.onFullScreen)h.onFullScreen(Fe);if(h.onFullscreen)h.onFullscreen(Fe)}Ne=a;T=b;"undefined"==typeof Ne&&(Ne=!0);"undefined"==
typeof T&&(T=!1);var d=h.canvas;Me||(Me=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):
null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Rf(a,b,c){var d=W&&0<W.attributes[139276]?hf:1;b&&c?(a.Mf=b,a.Gf=c):(b=a.Mf,c=a.Gf);var e=b,f=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(e/f<h.forcedAspectRatio?e=Math.round(f*h.forcedAspectRatio):f=Math.round(e/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/e,screen.height/
f);e=Math.round(e*g);f=Math.round(f*g)}T&&(b=e,c=f);e=Math.floor(b*d);d=Math.floor(c*d);a.width!=e&&(a.width=e);a.height!=d&&(a.height=d);"undefined"!=typeof a.style&&(e!=b||d!=c?(a.style.setProperty("width",b+"px","important"),a.style.setProperty("height",c+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height")))}
function Sf(a,b){var c=h.canvas.getBoundingClientRect(),d=h.canvas.clientHeight;a-=("undefined"!=typeof window.scrollX?window.scrollX:window.pageXOffset)+c.left;b-=("undefined"!=typeof window.scrollY?window.scrollY:window.pageYOffset)+c.top;a*=h.canvas.clientWidth/c.width;b*=d/c.height;return{x:a,y:b}}function Tf(){return"number"==typeof devicePixelRatio&&devicePixelRatio||1}function Uf(){const a=h.canvas;Re(a,a.clientWidth,a.clientHeight);bf()}
function Vf(){hf=Tf();W&&W.wf&&Wf(W.wf,W.id,hf,hf);Uf()}var Yf=a=>{var b=$a(a)+1,c=Xf(b);C(a,u,c,b);return c},Zf=a=>{try{a()}catch(b){ra(b)}};function $f(){var a=X,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{ag.push(c);try{return d(...e)}finally{n||(ag.pop(),Y&&1===bg&&0===ag.length&&(bg=0,Zf(cg),"undefined"!=typeof Fibers&&Fibers.Wg()))}}:d;return b}var bg=0,Y=null,dg=0,ag=[],eg={},fg={},gg=0,hg=null,ig=[];
function jg(){return new Promise((a,b)=>{hg={resolve:a,reject:b}})}function kg(){var a=Q(24588),b=a+12;x[a>>2]=b;x[a+4>>2]=b+24576;b=ag[0];var c=eg[b];void 0===c&&(c=gg++,eg[b]=c,fg[c]=b);w[a+8>>2]=c;return a}
function lg(a){if(!n){if(0===bg){var b=!1,c=!1;a((d=0)=>{if(!n&&(dg=d,b=!0,c)){bg=2;Zf(()=>mg(Y));"undefined"!=typeof df&&je&&Ee();d=!1;try{var e=(0,X[fg[w[Y+8>>2]]])()}catch(m){e=m,d=!0}var f=!1;if(!Y){var g=hg;g&&(hg=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(bg=1,Y=kg(),"undefined"!=typeof df&&je&&De(),Zf(()=>ng(Y)))}else 2===bg?(bg=0,Zf(og),Nf(Y),Y=null,ig.forEach(we)):ra(`invalid state: ${bg}`);return dg}}
var rg=(a,b,c,d,e)=>{function f(t){--ze;0!==p&&pg(p);return"string"===b?t?B(u,t):"":"boolean"===b?!!t:t}var g={string:t=>{var A=0;null!==t&&void 0!==t&&0!==t&&(A=Yf(t));return A},array:t=>{var A=Xf(t.length);r.set(t,A);return A}};a=h["_"+a];var m=[],p=0;if(d)for(var q=0;q<d.length;q++){var v=g[c[q]];v?(0===p&&(p=qg()),m[q]=v(d[q])):m[q]=d[q]}c=Y;d=a(...m);e=e?.async;ze+=1;if(Y!=c)return jg().then(f);d=f(d);return e?Promise.resolve(d):d};[44].forEach(a=>{jb[a]=new D(a);jb[a].stack="<generic error, no stack>"});
sb=Array(4096);Fb(E,"/");G("/tmp");G("/home");G("/home/web_user");(function(){G("/dev");cb(259,{read:()=>0,write:(d,e,f,g)=>g});Hb("/dev/null",259);bb(1280,eb);bb(1536,fb);Hb("/dev/tty",1280);Hb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Xa(a).byteLength);return a[--b]};Qb("random",c);Qb("urandom",c);G("/dev/shm");G("/dev/shm/tmp")})();
(function(){G("/proc");var a=G("/proc/self");G("/proc/self/fd");Fb({We(){var b=ib(a,"fd",16895,73);b.Oe={lookup(c,d){var e=F(+d);c={parent:null,We:{Wf:"fake"},Oe:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();for(var N,Z=0;32>Z;++Z)ld.push(Array(Z));var sg=new Float32Array(288);for(Z=0;288>Z;++Z)Rd[Z]=sg.subarray(0,Z+1);var tg=new Int32Array(288);for(Z=0;288>Z;++Z)Td[Z]=tg.subarray(0,Z+1);h.requestFullscreen=Oe;h.requestAnimationFrame=oe;h.setCanvasSize=cf;
h.pauseMainLoop=De;h.resumeMainLoop=Ee;h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=Le;
var ug={d:function(){var a="#"+h.canvas.id,b=$a(a)+1,c=Q(b);C(a,u,c,b);return c},a:(a,b,c,d)=>{ra(`Assertion failed: ${a?B(u,a):""}, at: `+[b?b?B(u,b):"":"unknown filename",c,d?d?B(u,d):"":"unknown function"])},Va:(a,b)=>dynCall_vi(a,b),fb:function(a,b,c){try{b=b?B(u,b):"";b=Sb(a,b);if(c&-8)return-28;var d=wb(b,{Cf:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Ab(d,a)?-2:0}catch(e){if("undefined"==typeof H||"ErrnoError"!==e.name)throw e;return-e.Se}},K:function(a,
b,c){Tb=c;try{var d=F(a);switch(b){case 0:var e=I();if(0>e)break;for(;qb[e];)e++;return Eb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=I(),d.flags|=e,0;case 12:return e=I(),ua[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof H||"ErrnoError"!==f.name)throw f;return-f.Se}},Za:function(a,b){try{if(0===b)return-28;var c=$a("/")+1;if(b<c)return-68;C("/",u,a,b);return c}catch(d){if("undefined"==typeof H||"ErrnoError"!==d.name)throw d;return-d.Se}},
ab:function(a,b,c){Tb=c;try{var d=F(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Xe.kg){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=I();w[e>>2]=25856;w[e+4>>2]=5;w[e+8>>2]=191;w[e+12>>2]=35387;for(var f=0;32>f;f++)r[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Xe.lg)for(e=I(),a=[],f=0;32>f;f++)a.push(r[e+f+17]);return 0;case 21519:if(!d.tty)return-59;
e=I();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=I();if(!d.xe.jg)throw new D(59);return d.xe.jg(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Xe.mg&&(f=[24,80],e=I(),ua[e>>1]=f[0],ua[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return-g.Se}},cb:function(a,b,c,d){Tb=d;try{b=b?B(u,b):"";b=Sb(a,b);var e=d?I():0;return Jb(b,c,e).fd}catch(f){if("undefined"==typeof H||
"ErrnoError"!==f.name)throw f;return-f.Se}},db:()=>1,Xa:()=>{Qa=!1;ze=0},Ra:function(a,b,c,d,e,f,g){f=g+2097152>>>0<4194305-!!f?(f>>>0)+4294967296*g:NaN;try{var m=F(e);if(c&2){if(32768!==(m.node.mode&61440))throw new D(43);if(!(d&2)){var p=u.slice(a,a+b);m.xe.sf&&m.xe.sf(m,p,f,b,d)}}}catch(q){if("undefined"==typeof H||"ErrnoError"!==q.name)throw q;return-q.Se}},Ya:()=>{ra("")},p:(a,b,c)=>{b=Vb(b,c);return Oa[a](...b)},q:(a,b,c)=>{b=Vb(b,c);return Oa[a](...b)},eb:()=>Date.now(),P:(a,b,c)=>{a=J(a);
if(!a)return-4;a=oc(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},wa:(a,b)=>{if(0>a||a>=dc.length)return-5;if(!dc[a])return-7;pc(b,dc[a]);return 0},y:qc,ya:()=>dc.length,Qd:Mc,Pd:Nc,ge:(a,b)=>{N.Ve.beginQueryEXT(a,M[b])},Od:Oc,Nd:Pc,Md:(a,b)=>{N.bindFramebuffer(a,yc[b])},Ld:(a,b)=>{N.bindRenderbuffer(a,zc[b])},Kd:Qc,Zd:a=>{N.bindVertexArray(Bc[a])},Jd:(a,b,c,d)=>N.blendColor(a,b,c,d),Id:a=>N.blendEquation(a),Gd:(a,b)=>N.blendEquationSeparate(a,b),Fd:Rc,Ed:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),Dd:Sc,
Cd:Tc,Bd:a=>N.checkFramebufferStatus(a),Ad:Uc,zd:Vc,yd:Wc,xd:a=>N.clearStencil(a),vd:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},ud:Xc,td:Yc,sd:(a,b,c,d,e,f,g,m,p)=>{N.compressedTexSubImage2D(a,b,c,d,e,f,g,p?u.subarray(p,p+m):null)},rd:(a,b,c,d,e,f,g,m)=>N.copyTexImage2D(a,b,c,d,e,f,g,m),qd:(a,b,c,d,e,f,g,m)=>N.copyTexSubImage2D(a,b,c,d,e,f,g,m),pd:Zc,od:$c,nd:ad,md:bd,ld:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=yc[d];e&&(N.deleteFramebuffer(e),e.name=0,yc[d]=null)}},kd:cd,ie:(a,b)=>{for(var c=
0;c<a;c++){var d=w[b+4*c>>2],e=M[d];e&&(N.Ve.deleteQueryEXT(e),M[d]=null)}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=zc[d];e&&(N.deleteRenderbuffer(e),e.name=0,zc[d]=null)}},id:dd,hd:ed,Yd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];N.deleteVertexArray(Bc[d]);Bc[d]=null}},gd:fd,fd:a=>{N.depthMask(!!a)},ed:(a,b)=>N.depthRange(a,b),dd:gd,cd:hd,bd:jd,ad:kd,Ud:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},Vd:(a,b)=>{for(var c=ld[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];N.drawBuffers(c)},$c:md,Td:(a,
b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},_c:nd,Zc:od,fe:a=>{N.Ve.endQueryEXT(a)},Yc:()=>N.finish(),Xc:()=>N.flush(),Wc:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,zc[d])},Vc:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Ac[d],e)},Uc:pd,Tc:qd,Rc:(a,b)=>{Gc(a,b,"createFramebuffer",yc)},je:(a,b)=>{for(var c=0;c<a;c++){var d=N.Ve.createQueryEXT();if(!d){for(P||=1282;c<a;)w[b+4*c++>>2]=0;break}var e=Fc(M);d.name=e;M[e]=d;w[b+4*c>>2]=e}},Qc:(a,b)=>{Gc(a,b,"createRenderbuffer",zc)},Pc:rd,Xd:(a,b)=>{Gc(a,
b,"createVertexArray",Bc)},Sc:a=>N.generateMipmap(a),Oc:(a,b,c,d,e,f,g)=>{sd("getActiveAttrib",a,b,c,d,e,f,g)},Nc:(a,b,c,d,e,f,g)=>{sd("getActiveUniform",a,b,c,d,e,f,g)},Mc:(a,b,c,d)=>{a=N.getAttachedShaders(K[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=L.indexOf(a[b])},Lc:td,Kc:(a,b)=>ud(a,b,4),Jc:(a,b,c)=>{c?w[c>>2]=N.getBufferParameter(a,b):P||=1281},Ic:()=>{var a=N.getError()||P;P=0;return a},Hc:vd,Gc:(a,b,c,d)=>{a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof
WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Fc:(a,b)=>ud(a,b,0),Dc:wd,Ec:xd,$d:yd,ce:zd,_d:yd,ae:zd,de:(a,b,c)=>{c?w[c>>2]=N.Ve.getQueryEXT(a,b):P||=1281},Cc:(a,b,c)=>{c?w[c>>2]=N.getRenderbufferParameter(a,b):P||=1281},Ac:Ad,zc:(a,b,c,d)=>{a=N.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},yc:(a,b,c,d)=>{if(a=N.getShaderSource(L[a]))b=0<b&&d?C(a,u,d,b):0,c&&(w[c>>2]=b)},Bc:Bd,xc:Ed,wc:(a,b,c)=>{c?y[c>>2]=N.getTexParameter(a,b):P||=
1281},vc:(a,b,c)=>{c?w[c>>2]=N.getTexParameter(a,b):P||=1281},sc:Hd,uc:(a,b,c)=>{Id(a,b,c,2)},tc:(a,b,c)=>{Id(a,b,c,0)},pc:(a,b,c)=>{c?w[c>>2]=N.getVertexAttribOffset(a,b):P||=1281},rc:(a,b,c)=>{Jd(a,b,c,2)},qc:(a,b,c)=>{Jd(a,b,c,5)},oc:(a,b)=>N.hint(a,b),nc:a=>(a=xc[a])?N.isBuffer(a):0,mc:a=>N.isEnabled(a),lc:a=>(a=yc[a])?N.isFramebuffer(a):0,kc:a=>(a=K[a])?N.isProgram(a):0,he:a=>(a=M[a])?N.Ve.isQueryEXT(a):0,jc:a=>(a=zc[a])?N.isRenderbuffer(a):0,ic:a=>(a=L[a])?N.isShader(a):0,hc:a=>(a=Ac[a])?N.isTexture(a):
0,Wd:a=>(a=Bc[a])?N.isVertexArray(a):0,gc:a=>N.lineWidth(a),fc:Kd,ec:Ld,dc:(a,b)=>N.polygonOffset(a,b),ee:(a,b)=>{N.Ve.queryCounterEXT(M[a],b)},cc:Nd,bc:()=>{},ac:(a,b,c,d)=>N.renderbufferStorage(a,b,c,d),$b:(a,b)=>{N.sampleCoverage(a,!!b)},_b:(a,b,c,d)=>N.scissor(a,b,c,d),Zb:()=>{P||=1280},Yb:Od,Xb:(a,b,c)=>N.stencilFunc(a,b,c),Wb:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),Vb:a=>N.stencilMask(a),Ub:(a,b)=>N.stencilMaskSeparate(a,b),Tb:(a,b,c)=>N.stencilOp(a,b,c),Sb:(a,b,c,d)=>N.stencilOpSeparate(a,
b,c,d),Rb:Pd,Qb:(a,b,c)=>N.texParameterf(a,b,c),Pb:(a,b,c)=>{N.texParameterf(a,b,y[c>>2])},Ob:Qd,Nb:(a,b,c)=>{N.texParameteri(a,b,w[c>>2])},Mb:(a,b,c,d,e,f,g,m,p)=>{p=p?Md(m,g,e,f,p):null;N.texSubImage2D(a,b,c,d,e,f,g,m,p)},Lb:(a,b)=>{N.uniform1f(R(a),b)},Kb:(a,b,c)=>{if(288>=b)for(var d=Rd[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);N.uniform1fv(R(a),d)},Jb:Sd,Ib:(a,b,c)=>{if(288>=b)for(var d=Td[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);N.uniform1iv(R(a),
d)},Hb:(a,b,c)=>{N.uniform2f(R(a),b,c)},Gb:(a,b,c)=>{if(144>=b)for(var d=Rd[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);N.uniform2fv(R(a),d)},Fb:(a,b,c)=>{N.uniform2i(R(a),b,c)},Eb:(a,b,c)=>{if(144>=b)for(var d=Td[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);N.uniform2iv(R(a),d)},Db:(a,b,c,d)=>{N.uniform3f(R(a),b,c,d)},Cb:(a,b,c)=>{if(96>=b)for(var d=Rd[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=
y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);N.uniform3fv(R(a),d)},Bb:(a,b,c,d)=>{N.uniform3i(R(a),b,c,d)},Ab:(a,b,c)=>{if(96>=b)for(var d=Td[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);N.uniform3iv(R(a),d)},zb:Ud,yb:(a,b,c)=>{if(72>=b){var d=Rd[4*b-1],e=y;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=y.subarray(c>>2,c+16*b>>2);N.uniform4fv(R(a),
d)},xb:(a,b,c,d,e)=>{N.uniform4i(R(a),b,c,d,e)},wb:(a,b,c)=>{if(72>=b)for(var d=Td[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);N.uniform4iv(R(a),d)},vb:(a,b,c,d)=>{if(72>=b)for(var e=Rd[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(R(a),!!c,e)},ub:(a,b,c,d)=>{if(32>=b)for(var e=Rd[9*b-
1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(R(a),!!c,e)},tb:Vd,sb:Wd,rb:a=>{N.validateProgram(K[a])},qb:(a,b)=>N.vertexAttrib1f(a,b),pb:(a,b)=>{N.vertexAttrib1f(a,y[b>>2])},ob:(a,b,c)=>N.vertexAttrib2f(a,b,c),nb:(a,b)=>{N.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},mb:(a,b,
c,d)=>N.vertexAttrib3f(a,b,c,d),lb:(a,b)=>{N.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},kb:(a,b,c,d,e)=>N.vertexAttrib4f(a,b,c,d,e),ib:(a,b)=>{N.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},Rd:(a,b)=>{N.vertexAttribDivisor(a,b)},hb:Xd,gb:Yd,Ua:a=>{var b=u.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=(e.min.call(e,2147483648,d+(65536-d%65536)%65536)-sa.buffer.byteLength+65535)/65536;try{sa.grow(e);
wa();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},za:Zd,ca:(a,b,c,d)=>$d(a,b,c,d,12,"blur"),ke:(a,b,c)=>{a=J(a);if(!a)return-4;a.width=b;a.height=c;return 0},_:(a,b,c,d)=>ae(a,b,c,d,4,"click"),ba:(a,b,c,d)=>$d(a,b,c,d,13,"focus"),da:(a,b,c,d)=>{if(!document.fullscreenEnabled&&!document.webkitFullscreenEnabled)return-1;a=J(a);if(!a)return-4;be(a,b,c,d,"webkitfullscreenchange");return be(a,b,c,d,"fullscreenchange")},T:(a,b,c)=>Zd()?-1:ce(a,b,c,26,"gamepadconnected"),S:(a,b,c)=>Zd()?-1:
ce(a,b,c,27,"gamepaddisconnected"),Y:(a,b,c,d)=>ae(a,b,c,d,8,"mousemove"),Z:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Lg||document.body.Zg||document.body.Ng))return-1;a=J(a);if(!a)return-4;de(a,b,c,d,"mozpointerlockchange");de(a,b,c,d,"webkitpointerlockchange");de(a,b,c,d,"mspointerlockchange");return de(a,b,c,d,"pointerlockchange")},$:(a,b,c,d)=>ee(a,b,c,d),U:(a,b,c,d)=>fe(a,b,c,d,25,"touchcancel"),W:(a,b,c,d)=>fe(a,b,c,d,23,"touchend"),V:(a,b,c,
d)=>fe(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>fe(a,b,c,d,22,"touchstart"),aa:(a,b,c)=>nc[1]?ge(a,b,c):-4,Ba:a=>document.title=a?B(u,a):"",Da:a=>lg(b=>Ce(b,a)),j:Be,L:function(a){try{var b=F(a);Lb(b);return 0}catch(c){if("undefined"==typeof H||"ErrnoError"!==c.name)throw c;return c.Se}},$a:function(a,b,c,d){try{a:{var e=F(a);a=b;for(var f,g=b=0;g<c;g++){var m=x[a>>2],p=x[a+4>>2];a+=8;var q=e,v=f,t=r;if(0>p||0>v)throw new D(28);if(null===q.fd)throw new D(8);if(1===(q.flags&2097155))throw new D(8);if(16384===
(q.node.mode&61440))throw new D(31);if(!q.xe.read)throw new D(28);var A="undefined"!=typeof v;if(!A)v=q.position;else if(!q.seekable)throw new D(70);var O=q.xe.read(q,t,m,p,v);A||(q.position+=O);var ja=O;if(0>ja){var Cf=-1;break a}b+=ja;if(ja<p)break;"undefined"!==typeof f&&(f+=ja)}Cf=b}x[d>>2]=Cf;return 0}catch(uc){if("undefined"==typeof H||"ErrnoError"!==uc.name)throw uc;return uc.Se}},Ta:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=F(a);
Mb(f,b,d);Na=[f.position>>>0,(Ma=f.position,1<=+Math.abs(Ma)?0<Ma?+Math.floor(Ma/4294967296)>>>0:~~+Math.ceil((Ma-+(~~Ma>>>0))/4294967296)>>>0:0)];w[e>>2]=Na[0];w[e+4>>2]=Na[1];f.Ff&&0===b&&0===d&&(f.Ff=null);return 0}catch(g){if("undefined"==typeof H||"ErrnoError"!==g.name)throw g;return g.Se}},_a:function(a,b,c,d){try{a:{var e=F(a);a=b;for(var f,g=b=0;g<c;g++){var m=x[a>>2],p=x[a+4>>2];a+=8;var q=Nb(e,r,m,p,f);if(0>q){var v=-1;break a}b+=q;"undefined"!==typeof f&&(f+=q)}v=b}x[d>>2]=v;return 0}catch(t){if("undefined"==
typeof H||"ErrnoError"!==t.name)throw t;return t.Se}},O:Mc,H:Nc,f:Oc,c:Pc,i:Qc,be:Rc,m:Sc,s:Tc,N:Uc,A:Vc,wd:Wc,Ia:Xc,Ma:Yc,Ga:Zc,Ka:$c,qa:ad,l:bd,F:cd,x:dd,M:ed,Sd:fd,J:gd,xa:hd,t:jd,Sa:kd,Qa:md,E:nd,h:od,Hd:pd,n:qd,Oa:rd,u:td,fa:vd,Ea:wd,G:xd,Ha:Ad,I:Bd,o:Ed,v:Hd,Fa:Kd,Pa:Ld,La:Nd,Ja:Od,Na:Pd,r:Qd,bb:Sd,jb:Ud,k:Vd,w:Wd,g:Xd,z:Yd,C:(a,b,c,d,e)=>{var f;for(f=0;f<U.length&&null!==U[f];f++);if(0<f)throw"glfwCreateWindow only supports one window at time currently";var g=f+1;if(0>=a||0>=b)g=0;else{d?Oe():
cf(a,b);for(f=0;f<U.length&&null==U[f];f++);a=0<ff[139265];f==U.length&&(a?h.cf=Le(h.canvas,!0,!0,{antialias:1<ff[135181],depth:0<ff[135173],stencil:0<ff[135174],alpha:0<ff[135172]}):Ie());!h.cf&&a?g=0:(f=h.canvas,c=new ef(g,f.clientWidth,f.clientHeight,f.width,f.height,c,e),g-1==U.length?U.push(c):U[g-1]=c,W=c,Uf(),g=c.id)}return g},ta:()=>{ff=Object.assign({},mf)},R:a=>{a:{if(a=V(a)){a.bg&&dynCall_vi(a.bg,a.id);U[a.id-1]=null;W.id==a.id&&(W=null);for(a=0;a<U.length;a++)if(null!==U[a]){a=void 0;
break a}h.cf=void 0}a=void 0}return a},D:()=>1,b:()=>qc()/1E3-jf,sa:(a,b)=>w[b>>2]=0,ua:()=>{if(U)return 1;jf=qc()/1E3;ff=Object.assign({},mf);U=[];W=null;hf=Tf();window.addEventListener("gamepadconnected",tf,!0);window.addEventListener("gamepaddisconnected",uf,!0);window.addEventListener("keydown",vf,!0);window.addEventListener("keypress",pf,!0);window.addEventListener("keyup",wf,!0);window.addEventListener("blur",xf,!0);kf=window.matchMedia("(resolution: "+Tf()+"dppx)");kf.addEventListener("change",
Vf);h.canvas.addEventListener("touchmove",zf,!0);h.canvas.addEventListener("touchstart",Ff,!0);h.canvas.addEventListener("touchcancel",Gf,!0);h.canvas.addEventListener("touchend",Gf,!0);h.canvas.addEventListener("mousemove",zf,!0);h.canvas.addEventListener("mousedown",Ff,!0);h.canvas.addEventListener("mouseup",Gf,!0);h.canvas.addEventListener("wheel",Hf,!0);h.canvas.addEventListener("mousewheel",Hf,!0);h.canvas.addEventListener("mouseenter",Af,!0);h.canvas.addEventListener("mouseleave",Bf,!0);h.canvas.addEventListener("drop",
Of,!0);h.canvas.addEventListener("dragover",Pf,!0);Oe=Qf;Ye=Sf;Re=Rf;af.push((a,b)=>{if(W&&0<W.attributes[139276]){var c=h.canvas;Jf(c.clientWidth,c.clientHeight,a,b)}else Jf(a,b,a,b)});return 1},ea:()=>{},ka:(a,b)=>{if(a=V(a)){var c=a.hf;a.hf=b;b=c}else b=null;return b},ga:(a,b)=>{a=V(a);if(!a)return null;var c=a.df;a.df=b;return c},ia:(a,b)=>{if(a=V(a)){var c=a.ef;a.ef=b;b=c}else b=null;return b},na:(a,b)=>{if(a=V(a)){var c=a.ff;a.ff=b;b=c}else b=null;return b},va:a=>{var b=gf;gf=a;return b},la:(a,
b)=>{if(a=V(a)){var c=a.kf;a.kf=b;b=c}else b=null;return b},ja:(a,b)=>{if(a=V(a)){var c=a.rf;a.rf=b;b=c}else b=null;return b},ha:(a,b)=>{if(a=V(a)){var c=a.uf;a.uf=b;b=c}else b=null;return b},ma:(a,b)=>{a=V(a);if(!a)return null;var c=a.wf;a.wf=b;return c},oa:(a,b)=>{a=V(a);if(!a)return null;var c=a.cg;a.cg=b;return c},pa:(a,b)=>{a=V(a);if(!a)return null;var c=a.dg;a.dg=b;return c},Q:(a,b)=>{if(a=V(a))a.qg=b},Ca:(a,b,c)=>{(a=V(a))&&W.id==a.id&&cf(b,c)},ra:(a,b)=>{if(a=V(a)){var c=a.xf;a.xf=b;b=c}else b=
null;return b},Aa:()=>{},B:()=>{window.removeEventListener("gamepadconnected",tf,!0);window.removeEventListener("gamepaddisconnected",uf,!0);window.removeEventListener("keydown",vf,!0);window.removeEventListener("keypress",pf,!0);window.removeEventListener("keyup",wf,!0);window.removeEventListener("blur",xf,!0);h.canvas.removeEventListener("touchmove",zf,!0);h.canvas.removeEventListener("touchstart",Ff,!0);h.canvas.removeEventListener("touchcancel",Gf,!0);h.canvas.removeEventListener("touchend",Gf,
!0);h.canvas.removeEventListener("mousemove",zf,!0);h.canvas.removeEventListener("mousedown",Ff,!0);h.canvas.removeEventListener("mouseup",Gf,!0);h.canvas.removeEventListener("wheel",Hf,!0);h.canvas.removeEventListener("mousewheel",Hf,!0);h.canvas.removeEventListener("mouseenter",Af,!0);h.canvas.removeEventListener("mouseleave",Bf,!0);h.canvas.removeEventListener("drop",Of,!0);h.canvas.removeEventListener("dragover",Pf,!0);kf&&kf.removeEventListener("change",Vf);h.canvas.width=h.canvas.height=1;W=
U=null},e:(a,b)=>{ff[a]=b},Wa:Ae},X=function(){function a(c){X=c.exports;X=$f();sa=X.le;wa();ya.unshift(X.me);Ca--;h.monitorRunDependencies?.(Ca);0==Ca&&(null!==Da&&(clearInterval(Da),Da=null),Ea&&(c=Ea,Ea=null,c()));return X}var b={a:ug};Ca++;h.monitorRunDependencies?.(Ca);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l(`Module.instantiateWasm callback failed with error: ${c}`),!1}La(b,function(c){a(c.instance)});return{}}(),Nf=a=>(Nf=X.ne)(a),Q=a=>(Q=X.oe)(a);
h._ma_device__on_notification_unlocked=a=>(h._ma_device__on_notification_unlocked=X.pe)(a);h._ma_malloc_emscripten=(a,b)=>(h._ma_malloc_emscripten=X.qe)(a,b);h._ma_free_emscripten=(a,b)=>(h._ma_free_emscripten=X.re)(a,b);h._ma_device_process_pcm_frames_capture__webaudio=(a,b,c)=>(h._ma_device_process_pcm_frames_capture__webaudio=X.se)(a,b,c);h._ma_device_process_pcm_frames_playback__webaudio=(a,b,c)=>(h._ma_device_process_pcm_frames_playback__webaudio=X.te)(a,b,c);
h._setWaitingForGist=()=>(h._setWaitingForGist=X.ue)();h._loadCodeFromJS=a=>(h._loadCodeFromJS=X.ve)(a);
var vg=h._main=(a,b,c)=>(vg=h._main=X.we)(a,b,c),lb=(a,b)=>(lb=X.ye)(a,b),qg=()=>(qg=X.ze)(),pg=a=>(pg=X.Ae)(a),Xf=a=>(Xf=X.Be)(a),S=h.dynCall_iiii=(a,b,c,d)=>(S=h.dynCall_iiii=X.Ce)(a,b,c,d),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=X.De)(a,b,c),If=h.dynCall_viii=(a,b,c,d)=>(If=h.dynCall_viii=X.Ee)(a,b,c,d),Wf=h.dynCall_viff=(a,b,c,d)=>(Wf=h.dynCall_viff=X.Fe)(a,b,c,d),qf=h.dynCall_viiiii=(a,b,c,d,e,f)=>(qf=h.dynCall_viiiii=X.Ge)(a,b,c,d,e,f),Df=h.dynCall_viiii=(a,b,c,d,e)=>(Df=
h.dynCall_viiii=X.He)(a,b,c,d,e),yf=h.dynCall_vidd=(a,b,c,d)=>(yf=h.dynCall_vidd=X.Ie)(a,b,c,d),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=X.Je)(a,b),ng=a=>(ng=X.Ke)(a),cg=()=>(cg=X.Le)(),mg=a=>(mg=X.Me)(a),og=()=>(og=X.Ne)();h.___start_em_js=46462;h.___stop_em_js=46685;h.ccall=rg;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>rg(a,b,c,f,d)};h.stringToUTF8=(a,b,c)=>C(a,u,b,c);h.lengthBytesUTF8=$a;var wg;
Ea=function xg(){wg||yg();wg||(Ea=xg)};function zg(a=[]){var b=vg;a.unshift(ca);var c=a.length,d=Xf(4*(c+1)),e=d;a.forEach(g=>{x[e>>2]=Yf(g);e+=4});x[e>>2]=0;try{var f=b(c,d);Be(f,!0)}catch(g){ye(g)}}
function yg(){var a=ba;function b(){if(!wg&&(wg=!0,h.calledRun=!0,!n)){h.noFSInit||Ob||(Ob=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Qb("stdin",h.stdin):Ib("/dev/tty","/dev/stdin"),h.stdout?Qb("stdout",null,h.stdout):Ib("/dev/tty","/dev/stdout"),h.stderr?Qb("stderr",null,h.stderr):Ib("/dev/tty1","/dev/stderr"),Jb("/dev/stdin",0),Jb("/dev/stdout",1),Jb("/dev/stderr",1));tb=!1;Pa(ya);Pa(za);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Ag&&zg(a);if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Aa.unshift(c)}Pa(Aa)}}if(!(0<Ca)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ba();Pa(xa);0<Ca||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Ag=!0;h.noInitialRun&&(Ag=!1);yg();
